
sass:
  style: compressed
  load_paths:
    - _sass
    - css

page_gen-dirs: true

page_gen:

  ##### Courses #####

  - index_files: true
    data: 'courses'
    template: '_includes/courses/individual-template.liquid'
    name: 'courseName'
    dir: 'courses'

  ##### Course Note Sheets #####

  - index_files: true
    data: 'courses'
    template: '_includes/courses/notes-template.liquid'
    name: 'courseName'
    dir: 'courses/notesheets'
    extra:
      title-suffix: ' Notesheet'

  ##### Tours #####

  - index_files: true
    data: 'tours'
    template: '_includes/tours/individual-template.liquid'
    name: 'number'
    dir: 'tours'
    extra:
      title-prefix: 'Tour '

  ##### Tournaments #####

  - index_files: true
    data: 'tournaments'
    template: '_includes/tournaments/individual-template.liquid'
    name: 'tournamentName'
    dir: 'tournaments'
    extra:
      title-suffix: ' Tournament'

  ##### Tournament Note Sheets #####

  - index_files: true
    data: 'tournaments'
    template: '_includes/tournaments/notes-template.liquid'
    name: 'tournamentName'
    dir: 'tournaments/notesheets'
    extra:
      title-suffix: ' Tournament Notesheet'

  ################################################################
  # TODO: Would be nice to modify page generator to support some #
  # kind of nesting synax (e.g. data: 'courses.*.holes')         #
  ################################################################

  ##### Course Holes #####

  - index_files: true
    data: 'courses.Christmas.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/Christmas'
    extra:
      title-prefix: 'Christmas - Hole '
  - index_files: true
    data: 'courses.CityPark.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/CityPark'
    extra:
      title-prefix: 'City Park - Hole '
  - index_files: true
    data: 'courses.CreepyCliffs.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/CreepyCliffs'
    extra:
      title-prefix: 'Creepy Cliffs - Hole '
  - index_files: true
    data: 'courses.GlenmonarchEstate.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/GlenmonarchEstate'
    extra:
      title-prefix: 'Glenmonarch Estate - Hole '
  - index_files: true
    data: 'courses.GhostlyGlades.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/GhostlyGlades'
    extra:
      title-prefix: 'Ghostly Glades - Hole '
  - index_files: true
    data: 'courses.GokashoBay.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/GokashoBay'
    extra:
      title-prefix: 'Gokasho Bay - Hole '
  - index_files: true
    data: 'courses.GreenochPoint.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/GreenochPoint'
    extra:
      title-prefix: 'Greenoch Point - Hole '
  - index_files: true
    data: 'courses.HauntedHills.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/HauntedHills'
    extra:
      title-prefix: 'Haunted Hills - Hole '
  - index_files: true
    data: 'courses.JuniperPoint.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/JuniperPoint'
    extra:
      title-prefix: 'Juniper Point - Hole '
  - index_files: true
    data: 'courses.MeadowCastle.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/MeadowCastle'
    extra:
      title-prefix: 'Meadow Castle - Hole '
  - index_files: true
    data: 'courses.NamhaeCliffs.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/NamhaeCliffs'
    extra:
      title-prefix: 'Namhae Cliffs - Hole '
  - index_files: true
    data: 'courses.SakuraHills.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/SakuraHills'
    extra:
      title-prefix: 'Sakura Hills - Hole '
  - index_files: true
    data: 'courses.ParcdeParis.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/ParcdeParis'
    extra:
      title-prefix: 'Parc de Paris - Hole '
  - index_files: true
    data: 'courses.SantaVentura.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/SantaVentura'
    extra:
      title-prefix: 'Santa Ventura - Hole '
  - index_files: true
    data: 'courses.SouthernPines.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/SouthernPines'
    extra:
      title-prefix: 'Southern Pines - Hole '
  - index_files: true
    data: 'courses.SunshineGlades.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/SunshineGlades'
    extra:
      title-prefix: 'Sunshine Glades - Hole '
  - index_files: true
    data: 'courses.TheMilano.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/TheMilano'
    extra:
      title-prefix: 'The Milano - Hole '
  - index_files: true
    data: 'courses.TheOasis.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/TheOasis'
    extra:
      title-prefix: 'The Oasis - Hole '
  - index_files: true
    data: 'courses.PorthelloCove.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/PorthelloCove'
    extra:
      title-prefix: 'The Oasis - Hole '
  - index_files: true
    data: 'courses.Touchdown.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/Touchdown'
    extra:
      title-prefix: 'Touchdown - Hole '
  - index_files: true
    data: 'courses.VineyardAcres.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/VineyardAcres'
    extra:
      title-prefix: 'Vineyard Acres - Hole '
  - index_files: true
    data: 'courses.WinterLinks.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/WinterLinks'
    extra:
      title-prefix: 'Winter Links - Hole '
  - index_files: true
    data: 'courses.WinterOlympics.holes'
    template: '_includes/courses/hole-template.liquid'
    name: 'number'
    dir: 'courses/WinterOlympics'
    extra:
      title-prefix: 'Winter WinterOlympics - Hole '

  ##### Tournament Holes #####

  - index_files: true
    data: 'tournaments.USChampions.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/USChampions'
    extra:
      title-prefix: 'US Champions Tournament - Hole '
      tournamentName: 'US Champions'
  - index_files: true
    data: 'tournaments.AsiaPacific.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/AsiaPacific'
    extra:
      title-prefix: 'Asia Pacific Tournament - Hole '
      tournamentName: 'Asia Pacific'
  - index_files: true
    data: 'tournaments.WestCoast.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/WestCoast'
    extra:
      title-prefix: 'West Coast Tournament - Hole '
      tournamentName: 'West Coast'
  - index_files: true
    data: 'tournaments.4thOfJuly.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/4thOfJuly'
    extra:
      title-prefix: '4th Of July Tournament - Hole '
      tournamentName: '4th Of July'
  - index_files: true
    data: 'tournaments.UKChampions.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/UKChampions'
    extra:
      title-prefix: 'UK Champions Tournament - Hole '
      tournamentName: 'UK Champions'
  - index_files: true
    data: 'tournaments.SunshineOpen.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/SunshineOpen'
    extra:
      title-prefix: 'Sunshine Open Tournament - Hole '
      tournamentName: 'Sunshine Open'
  - index_files: true
    data: 'tournaments.SakuraClassic.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/SakuraClassic'
    extra:
      title-prefix: 'Sakura Classic Tournament - Hole '
      tournamentName: 'Sakura Classic'
  - index_files: true
    data: 'tournaments.LaborDay.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/LaborDay'
    extra:
      title-prefix: 'Labor Day Tournament - Hole '
      tournamentName: 'Labor Day'
  - index_files: true
    data: 'tournaments.WineValley.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/WineValley'
    extra:
      title-prefix: 'Wine Valley Tournament - Hole '
      tournamentName: 'Wine Valley'
  - index_files: true
    data: 'tournaments.HauntedHills.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/HauntedHills'
    extra:
      title-prefix: 'Haunted Hills Tournament - Hole '
      tournamentName: 'Haunted Hills'
  - index_files: true
    data: 'tournaments.CreepyCliffs.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/CreepyCliffs'
    extra:
      title-prefix: 'Creepy Cliffs Tournament - Hole '
      tournamentName: 'Creepy Cliffs'
  - index_files: true
    data: 'tournaments.CaliforniaClassic.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/CaliforniaClassic'
    extra:
      title-prefix: 'California Classic Tournament - Hole '
      tournamentName: 'California Classic'
  - index_files: true
    data: 'tournaments.Thanksgiving.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Thanksgiving'
    extra:
      title-prefix: 'Thanksgiving Tournament - Hole '
      tournamentName: 'Thanksgiving'
  - index_files: true
    data: 'tournaments.WinterLinks.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/WinterLinks'
    extra:
      title-prefix: 'Winter Links Tournament - Hole '
      tournamentName: 'Winter Links'
  - index_files: true
    data: 'tournaments.Christmas.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Christmas'
    extra:
      title-prefix: 'Christmas Tournament - Hole '
      tournamentName: 'Christmas'
  - index_files: true
    data: 'tournaments.1YearAnniversary.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/1YearAnniversary'
    extra:
      title-prefix: '1 Year Anniversary Tournament - Hole '
      tournamentName: '1 Year Anniversary'
  - index_files: true
    data: 'tournaments.Touchdown.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Touchdown'
    extra:
      title-prefix: 'Touchdown Tournament - Hole '
      tournamentName: 'Touchdown'
  - index_files: true
    data: 'tournaments.WinterGames.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/WinterGames'
    extra:
      title-prefix: 'Winter Games Tournament - Hole '
      tournamentName: 'Winter Games'
  - index_files: true
    data: 'tournaments.Hollywood.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Hollywood'
    extra:
      title-prefix: 'Hollywood Tournament - Hole '
      tournamentName: 'Hollywood'
  - index_files: true
    data: 'tournaments.StPatricks.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/StPatricks'
    extra:
      title-prefix: 'St. Patrick''s Tournament - Hole '
      tournamentName: 'St. Patrick''s'
  - index_files: true
    data: 'tournaments.EasterLinks.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/EasterLinks'
    extra:
      title-prefix: 'Easter Links Tournament - Hole '
      tournamentName: 'Easter Links'
  - index_files: true
    data: 'tournaments.SpringMajor2018.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/SpringMajor2018'
    extra:
      title-prefix: 'Spring Major 2018 Tournament - Hole '
      tournamentName: 'Spring Major 2018'
  - index_files: true
    data: 'tournaments.EarthDay.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/EarthDay'
    extra:
      title-prefix: 'Earth Day Tournament - Hole '
      tournamentName: 'Earth Day'
  - index_files: true
    data: 'tournaments.CincoDeMayo.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/CincoDeMayo'
    extra:
      title-prefix: 'Cinco De Mayo Tournament - Hole '
      tournamentName: 'Cinco De Mayo'
  - index_files: true
    data: 'tournaments.RoyalOpen.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/RoyalOpen'
    extra:
      title-prefix: 'Royal Open Tournament - Hole '
      tournamentName: 'Royal Open'
  - index_files: true
    data: 'tournaments.VegasSundown.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/VegasSundown'
    extra:
      title-prefix: 'Vegas Sundown Tournament - Hole '
      tournamentName: 'Vegas Sundown'
  - index_files: true
    data: 'tournaments.NewYorkClassic.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/NewYorkClassic'
    extra:
      title-prefix: 'New York Classic Tournament - Hole '
      tournamentName: 'New York Classic'
  - index_files: true
    data: 'tournaments.FootballFever.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/FootballFever'
    extra:
      title-prefix: 'Football Fever Tournament - Hole '
      tournamentName: 'Football Fever'
  - index_files: true
    data: 'tournaments.DesertOpen.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/DesertOpen'
    extra:
      title-prefix: 'Desert Open Tournament - Hole '
      tournamentName: 'Desert Open'
  - index_files: true
    data: 'tournaments.OriginLinks.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/OriginLinks'
    extra:
      title-prefix: 'Origin Links Tournament - Hole '
      tournamentName: 'Origin Links'
  - index_files: true
    data: 'tournaments.ClubOceania.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/ClubOceania'
    extra:
      title-prefix: 'Club Oceania Tournament - Hole '
      tournamentName: 'Club Oceania'
  - index_files: true
    data: 'tournaments.SummerMajor.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/SummerMajor'
    extra:
      title-prefix: 'Summer Major Tournament - Hole '
      tournamentName: 'Summer Major'
  - index_files: true
    data: 'tournaments.LaborDay2018.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/LaborDay2018'
    extra:
      title-prefix: 'Labor Day 2018 Tournament - Hole '
      tournamentName: 'Labor Day 2018'
  - index_files: true
    data: 'tournaments.Voyager.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Voyager'
    extra:
      title-prefix: 'Voyager Tournament - Hole '
      tournamentName: 'Voyager'
  - index_files: true
    data: 'tournaments.MetroOpen.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/MetroOpen'
    extra:
      title-prefix: 'Metro Open Tournament - Hole '
      tournamentName: 'Metro Open'
  - index_files: true
    data: 'tournaments.PlatinumResorts.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/PlatinumResorts'
    extra:
      title-prefix: 'Platinum Resorts Tournament - Hole '
      tournamentName: 'Platinum Resorts'
  - index_files: true
    data: 'tournaments.GhostlyGlades.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/GhostlyGlades'
    extra:
      title-prefix: 'Ghostly Glades Tournament - Hole '
      tournamentName: 'Ghostly Glades'
  - index_files: true
    data: 'tournaments.Mountain.holes'
    template: '_includes/tournaments/hole-template.liquid'
    name: 'number'
    dir: 'tournaments/Mountain'
    extra:
      title-prefix: 'Mountain Tournament - Hole '
      tournamentName: 'Mountain'
